version: '3.8'

services:
  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.1.1-java8
    container_name: hdfs-namenode
    environment:
      - CLUSTER_NAME=test-hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
    ports:
      - "9870:9870"   # Web UI (and WebHDFS)
      - "9000:9000"   # HDFS RPC
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.1.1-java8
    container_name: hdfs-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
      - HDFS_CONF_dfs_permissions_enabled=false
    depends_on:
      - hadoop
    ports:
      - "9864:9864"   # Datanode web UI
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hadoop-net

volumes:
  namenode:
  datanode:

networks:
  hadoop-net:
